name: Update IP Ranges

on:
  schedule:
    - cron: '30 0 * * *'  # 每天UTC时间00:30运行，相当于北京时间8:30
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]  # 当推送到main分支时也触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set timezone to Asia/Shanghai
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run all-chn-ip.py
      run: python all-chn-ip.py

    - name: Add timestamp to files
      run: |
        echo "# Last updated: $(date '+%Y-%m-%d %H:%M:%S')" >> cn-ipv4-cidr.txt
        echo "# Last updated: $(date '+%Y-%m-%d %H:%M:%S')" >> cn-ipv6-cidr.txt
        echo "# Last updated: $(date '+%Y-%m-%d %H:%M:%S')" >> delegated-apnic-latest

    - name: Commit and push
      run: |
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git add cn-ipv4-cidr.txt cn-ipv6-cidr.txt delegated-apnic-latest
        timestamp=$(date "+%Y-%m-%d %H:%M:%S")
        git commit -m "Update IP ranges - $timestamp" || echo "No changes to commit"
        git push

    - name: Error notification
      if: failure()
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Workflow failed: Update IP Ranges',
            body: 'The workflow failed. Please check the logs for more information.'
          })
